//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Utils.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatementSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatementSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Utils.Resources.StatementSql", typeof(StatementSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ba.AccountHolder
        ///   ,ba.AccountNumber
        ///   ,ba.Alias
        ///   ,b.Name [Bank]
        ///FROM users u
        ///INNER JOIN BankAccounts ba
        ///	ON u.Id = ba.UserId
        ///INNER JOIN Banks b
        ///	ON ba.BankId = b.Id
        ///WHERE u.UserName = &apos;admin&apos;
        ///AND ba.IsAdmin = 1.
        /// </summary>
        public static string getBankTopMai {
            get {
                return ResourceManager.GetString("getBankTopMai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Messages
        ///SET Readed=@readed
        ///WHERE Id=@idMessage;.
        /// </summary>
        public static string updateMeesageReaded {
            get {
                return ResourceManager.GetString("updateMeesageReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users
        ///SET Password=@password
        ///WHERE VerifiedEmail =1 
        ///AND Mail=@mail;.
        /// </summary>
        public static string updatePasswordByMail {
            get {
                return ResourceManager.GetString("updatePasswordByMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users
        ///SET Password=@password
        ///WHERE VerifiedPhone =1 
        ///AND Phone=@phone;.
        /// </summary>
        public static string updatePasswordByPhone {
            get {
                return ResourceManager.GetString("updatePasswordByPhone", resourceCulture);
            }
        }
    }
}
